/* Build: one engine, three targets.
 *   src/engine.js   — UMD source of truth (node tests + browser inline)
 *   src/engine.mjs  — ESM wrapper for the Worker
 *   public/index.html — the deployable page, engine inlined
 *   yourpost-sucks.html — identical standalone copy that works from file://
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const engine = readFileSync('src/engine.js', 'utf8');
const shell = readFileSync('shell.html', 'utf8');

if (!shell.includes('/*ENGINE*/')) throw new Error('shell.html lost its /*ENGINE*/ marker');

mkdirSync('public', { recursive: true });

writeFileSync('src/engine.mjs',
  '/* generated by build.mjs — do not edit. Source: src/engine.js */\n' +
  engine + '\nexport default globalThis.YourPostSucks;\n');

// NOTE: the replacement MUST be a function. A string replacement makes JS
// interpret $& / $` / $' inside the engine source as backreferences, which
// silently corrupts countPhrase's regex-escaping and breaks every phrase
// containing a regex metacharacter ("thoughts?", "agree?"). Guarded by
// parity.mjs, which compares browser-computed scores against node.
const page = shell.replace('/*ENGINE*/', () => engine);
writeFileSync('public/index.html', page);
writeFileSync('yourpost-sucks.html', page);

// The craft reference is authored as markdown and compiled into the Worker so
// the prompt and the human-readable doc can never drift apart.
const craft = readFileSync('post-craft-rules.md', 'utf8');
writeFileSync('src/craft-prompt.mjs',
  '/* generated by build.mjs from post-craft-rules.md — do not edit */\nexport default ' +
  JSON.stringify(craft) + ';\n');

const rules = (engine.match(/^\s*rule\(\{/gm) || []).length;
console.log(`built · ${rules} rules · ${(page.length / 1024).toFixed(0)} KB page`);
